version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python clean_data.py
    volumes:
      - .:/app

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: pytest test_clean_data.py
    volumes:
      - .:/app